### PR TITLE
Consider branch 6.0 as maintained

### PR DESCRIPTION
**Pull request by nicolas-grekas**

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
https://symfony.com/releases.json won't list `6.0` for the net 6 months.

**Comment by derrabus** [comment]
Can we use https://symfony.com/maintained-versions.json instead?

**Comment by nicolas-grekas** [comment]
PR updated.

**Review by derrabus — APPROVED** [review]

**Review by Nyholm — APPROVED** [review]

**Comment by weaverryan** [comment]
There is a failing test - but I'm going to get this merged and deployed. Thanks!

**Pull request merged**
