### PR TITLE
Add PasswordHasher to StaticLabelApi

### PR DESCRIPTION
**Pull request by chalasr**

### CODE REVIEW

**Review by wouterj — APPROVED** [review]

**Comment by Nyholm** [comment]
Thank you. 

Could you add to the class comment that the `StaticLabelApi` class is only used in tests?

**Comment by chalasr** [comment]
@Nyholm sure, done

**Comment by chalasr** [comment]
Now I know :) Thanks for confirming and merging!

**Comment by xabbuh** [comment]
@Nyholm label added

**Comment by Nyholm** [comment]
Thank you

**Pull request merged**
